name: Update GitHub Pages site

on:
  repository_dispatch:
    types: [update-data]

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages  # ✅ checkout the gh-pages branch
          submodules: false 


      - name: Pull data
        run: |
          git clone https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/nus-fuzzing-hackathon-2025/sql-fuzz-hackathon tmp-repo-data
          cp  tmp-repo-data/data/*.json ./

      - name: Build site
        run: |
          echo "build step here"
          python refresh.py
          echo $?
          cat index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.REPO_ACCESS_TOKEN }}
          publish_dir: .
